### ISSUE TITLE
Feature request: Use JSON instead of variables.xml 

### ISSUE THREAD

**Issue by cboulanger** [bandorko/docsify-variables#5]
Hi, we plan to use your plugin for the new documentation of https://www.qooxdoo.org/ 
One thing that strikes us as a bit odd is that the variables are taken from an XML file that, if I understand it correctly (please correct me if I am wrong) isn't actually valid XML, since the format would be
```xml
<qooxdoo>
  <version>6.0.0</version>
</qooxdoo>
<foo>
  <bar>Hello World!</bar>
</foo>
```
For our purposes (especially the build process), it would be much better to just have a JSON file 
```json
{
  "qooxdoo": {
    "version": "6.0.0."
  },
  "foo": {
    "bar": "Hello World"
  }
}
```
Would you consider supporting JSON for the variable data file?

**Comment by bandorko** [comment]
Hi,

XML files should be valid. In your case it should be
<var>`
  <qooxdoo>
    <version>6.0.0</version>
  </qooxdoo>
  <foo>
    <bar>Hello World!</bar>
  </foo>
</var>`

And you can reference values like ${var.gooxdoo.version}

I will try to support json files too.

**Comment by bandorko** [comment]
json is supported in version 1.3.0

**Comment by cboulanger** [comment]
That was quick, thank you very much!

**Comment by bandorko** [comment]
Please verify if the solution fits for your needs.

**Comment by cboulanger** [comment]
Yes, it works very well, thank you.

**Comment by bandorko** [comment]
Thanks! Then I close this issue.
